package:
  name: tomophantom
  version: 1.4.3

build:
  preserve_egg_dir: False
  number: 1

requirements:
  build:
    - python {{ python }}
    - numpy {{ numpy }}  
    - cython
    - cmake
    - blas=*=openblas # [not win]


  run:
    - python {{ python }}
    - numpy
    - vc 14 # [win and py==36]
    - vc 14 # [win and py==35]
    - libgcc-ng # [unix]

about:
  home: https://github.com/dkazanc/TomoPhantom
  license:  Apache 2.0 license
  summary: 'Tomography Phantom Data generator'
