package:
  name: tomophantom
  version: 1.4.3

build:
  preserve_egg_dir: False
  number: 1

requirements:
  build:
    - python {{ python }}
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - setuptools
    - cython
    - cmake
    - blas=*=openblas # [not win]


  run:
    - python {{ python }}
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - vc 14 # [win and py36]
    - vc 14 # [win and py35]
    - libgcc-ng # [unix]

about:
  home: https://github.com/dkazanc/TomoPhantom
  license:  Apache 2.0 license
  summary: 'Tomography Phantom Data generator'
